namespace: koonix
name: sshjuggle
version: 0.1.0
description: Role for finding a working set of ssh connection parameters amongst multiple.
repository: https://github.com/koonix/ansible-sshjuggle
issues:     https://github.com/koonix/ansible-sshjuggle/issues
authors: [ 'koonix <me@koonix.org>' ]
license: [ 'MIT' ]
readme: README.md
tags:
  - ssh
